/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as PrecioRouteImport } from './routes/precio'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as VenderRouteImport } from './routes/vender'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecioRoute = PrecioRouteImport.update({
  id: '/precio',
  path: '/precio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRoute
  '/precio': typeof PrecioRoute
  '/registrar': typeof RegistrarRoute
  '/vender': typeof VenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRoute
  '/precio': typeof PrecioRoute
  '/registrar': typeof RegistrarRoute
  '/vender': typeof VenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRoute
  '/precio': typeof PrecioRoute
  '/registrar': typeof RegistrarRoute
  '/vender': typeof VenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inventario' | '/precio' | '/registrar' | '/vender'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventario' | '/precio' | '/registrar' | '/vender'
  id: '__root__' | '/' | '/inventario' | '/precio' | '/registrar' | '/vender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventarioRoute: typeof InventarioRoute
  PrecioRoute: typeof PrecioRoute
  RegistrarRoute: typeof RegistrarRoute
  VenderRoute: typeof VenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precio': {
      id: '/precio'
      path: '/precio'
      fullPath: '/precio'
      preLoaderRoute: typeof PrecioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventarioRoute: InventarioRoute,
  PrecioRoute: PrecioRoute,
  RegistrarRoute: RegistrarRoute,
  VenderRoute: VenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}